/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.wildc.ucumari.client.base;

import com.wildc.ucumari.client.base.util.Constantes;
import com.wildc.ucumari.client.base.util.SwingUtils;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Paint;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Cristian
 */
public class UDialogBackPanel extends javax.swing.JPanel {
    //private static final Paint fill = new Color(0xAAFFFFFF, true);
    //private static final Paint fill = new Color(0xAAff0000, true);
    private static final Paint fill = Constantes.FILL_BACK_PANEL;
    //private static final ImageIcon shadowImage = new ImageIcon(SwingUtils.class.getResource("dialogShadow.png"));
    private final JComponent cmp;
    private final JLabel title = new JLabel();
    //private final JLabel info = new JLabel("Presione 'ESC' para cerrar la ventana");
    private final JLabel info = new JLabel();
    private final JPanel headPanel = new JPanel();
    private final JDialog dialog;

    /**
     * Creates new form UDialogBackPanel
     */
    public UDialogBackPanel(final JDialog dialog) {
        this.dialog = dialog;
        
        this.cmp = (JComponent) dialog.getContentPane();                        
                        
        ImageIcon image = null;
        image = new ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/close.png"));
        image.setImage(image.getImage().getScaledInstance(18,18, Image.SCALE_DEFAULT));
        info.setHorizontalAlignment(JLabel.CENTER);
        info.setVerticalAlignment(JLabel.CENTER);
        info.setIcon(image);
        info.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                SwingUtils.fadeOutFast(dialog);
            }
        });
        //info = new javax.swing.JLabel(image, JLabel.CENTER);

        //headPanel = new JPanel();
        //System.out.println(this.cmp.getPreferredSize());
        //se suma 8 por los bordes 4 por cada lado y 30 es estatico para el titulo
        headPanel.setSize(new Dimension(this.cmp.getPreferredSize().width+8, 30));
        //color Cabecera del dialog
        headPanel.setBackground(Constantes.BACKGROUND_DIALOG);

        //headPanel.setOpaque(false);
        //setBackground(new Color(100,50,50,100));
        setOpaque(false);
        //setBackground(Color.yellow);
        setLayout(null);
        add(cmp);
        add(title);
        add(info);
        add(headPanel);

        //cmp.setBorder(BorderFactory.createLineBorder(Color.WHITE, 4));
        LineBorder roundedLineBorder = new LineBorder(Constantes.BACKGROUND_DIALOG, 4, true);        
        cmp.setBorder(roundedLineBorder);
        //cmp.setBorder(BorderFactory.createLineBorder(new Color(119,136,153),4));

        title.setFont(new Font("Tahoma", Font.BOLD, 14));
        title.setForeground(Color.WHITE);
        info.setForeground(Color.BLACK);

        title.setText(" " + dialog.getTitle());
        title.setSize(title.getPreferredSize());
        info.setSize(info.getPreferredSize());
        cmp.setSize(cmp.getPreferredSize());
        
    }
    
    @Override
    protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            int w = getWidth();
            int h = getHeight();

            //int shadowX = w/2 - (cmp.getWidth()+100)/2;
            //int shadowY = h/2 - (cmp.getHeight()+100)/2;
            cmp.setLocation(w/2-cmp.getWidth()/2, h/2-cmp.getHeight()/2);
            title.setLocation(w/2-cmp.getWidth()/2+4, h/2-cmp.getHeight()/2-title.getHeight());
            info.setLocation(w/2+cmp.getWidth()/2-info.getWidth()-4, h/2-cmp.getHeight()/2-info.getHeight());
            headPanel.setLocation(w/2-cmp.getWidth()/2, h/2-cmp.getHeight()/2-info.getHeight()-6);

            Graphics2D gg = (Graphics2D) g.create();
            gg.setPaint(fill);
            gg.fillRect(0, 0, w, h);
            //gg.drawImage(shadowImage.getImage(), shadowX, shadowY, cmp.getWidth()+100, cmp.getHeight()+100, null);
            gg.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
