/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.wildc.ucumari.client.base;

import com.sun.awt.AWTUtilities;
import com.wildc.ucumari.client.base.util.SwingUtils;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JFrame;

/**
 *
 * @author Cristian
 */
public class UDialogBase extends javax.swing.JDialog {

    /**
     * Creates new form UDialogBase
     */
    public UDialogBase(JFrame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        AWTUtilities.setWindowOpaque(this, false);	
        
        //initComponents();
        
        container = new javax.swing.JPanel(){
        @Override
        public void paintComponent(Graphics g) {
            g.setColor(new Color(100,50,50,100));
            g.fillRect(0,0,getWidth(), getHeight());
        }};
        toolBar = new javax.swing.JPanel(){
        @Override
        public void paintComponent(Graphics g) {
            //super.paintComponent(g);
            g.setColor(new Color(200,50,50,100));
            g.fillRect(0,0,getWidth(), getHeight());
        }};
        btnNuevo = new com.wildc.ucumari.client.base.component.UToolBarButton();
        mainContainer = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g) {
                //super.paintComponent(g);
                g.setColor(new Color(100,50,50,100));
                g.fillRect(0,0,getWidth(), getHeight());
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        

        container.setPreferredSize(getPreferredSize());
        container.setLayout(new java.awt.BorderLayout());

        toolBar.setMinimumSize(new java.awt.Dimension(180, 30));
        toolBar.setPreferredSize(new java.awt.Dimension(180, 30));        
        toolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        btnNuevo.setBackground(new Color(100,50,50,100));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/agregar_disabled.png"))); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setMaximumSize(new java.awt.Dimension(60, 30));
        btnNuevo.setMinimumSize(new java.awt.Dimension(60, 30));
        btnNuevo.setPreferredSize(new java.awt.Dimension(60, 30));
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/agregar_enabled.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        toolBar.add(btnNuevo);

        container.add(toolBar, java.awt.BorderLayout.NORTH);

        mainContainer.setLayout(null);
        container.add(mainContainer, java.awt.BorderLayout.CENTER);

        container.setBackground(new Color(100,50,50,200)); 
        //container.setPreferredSize(new Dimension(getPreferredSize().width, getPreferredSize().height));
        container.setPreferredSize(new Dimension(500,350));
        container.setFocusable(true);
        container.requestFocusInWindow();

        getContentPane().add(container);
        //container.setBounds(0, 0, 400, 300);
        
        
        SwingUtils.createDialogBackPanel(this, parent.getContentPane());
        SwingUtils.addEscapeToCloseSupport(this, true);
        SwingUtils.fadeInFast(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        toolBar = new javax.swing.JPanel();
        btnNuevo = new com.wildc.ucumari.client.base.component.UToolBarButton();
        mainContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        container.setPreferredSize(getPreferredSize());
        container.setLayout(new java.awt.BorderLayout());

        toolBar.setMinimumSize(new java.awt.Dimension(180, 30));
        toolBar.setPreferredSize(new java.awt.Dimension(180, 30));
        toolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        btnNuevo.setBackground(new Color(100,50,50,100));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/agregar_disabled.png"))); // NOI18N
        btnNuevo.setMnemonic('N');
        btnNuevo.setToolTipText("Nuevo");
        btnNuevo.setMaximumSize(new java.awt.Dimension(60, 30));
        btnNuevo.setMinimumSize(new java.awt.Dimension(60, 30));
        btnNuevo.setPreferredSize(new java.awt.Dimension(60, 30));
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/agregar_enabled.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        toolBar.add(btnNuevo);

        container.add(toolBar, java.awt.BorderLayout.NORTH);

        mainContainer.setLayout(null);
        container.add(mainContainer, java.awt.BorderLayout.CENTER);

        container.setPreferredSize(new Dimension(400, 300));
        container.setFocusable(true);
        container.requestFocusInWindow();

        getContentPane().add(container);
        container.setBounds(0, 0, 400, 300);
        //container.setBounds(0, 0, getWidth(), getHeight());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wildc.ucumari.client.base.component.UToolBarButton btnNuevo;
    private javax.swing.JPanel container;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel toolBar;
    // End of variables declaration//GEN-END:variables
}
