/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.wildc.ucumari.client.base;

import com.sun.awt.AWTUtilities;
import com.wildc.ucumari.client.base.component.UMessage;
import com.wildc.ucumari.client.base.component.UPanelMant;
import com.wildc.ucumari.client.base.util.Constantes;
import com.wildc.ucumari.client.base.util.SwingUtils;
import javax.swing.JFrame;

/**
 *
 * @author cmontes
 */
public class UDialogMantBase extends javax.swing.JDialog {

    JFrame parent;
    /**
     * Creates new form UDialogMantBase
     */
    public UDialogMantBase(JFrame parent, String title, boolean modal, UPanelMant mainPanel) {
        super(parent, title, modal);
        this.parent =  parent;
        this.mainPanel = mainPanel;
        setUndecorated(true);
        AWTUtilities.setWindowOpaque(this, false);
        initComponents();
        //SwingUtils.createDialogBackPanel(this, parent.getContentPane());
        this.setSize(mainPanel.getWidth(), mainPanel.getHeight() + 33);
        
        SwingUtils.createDialogBackPanel(this, parent.getContentPane());
        SwingUtils.addEscapeToCloseSupport(this, true);
        SwingUtils.fadeInFast(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new com.wildc.ucumari.client.base.component.UPanel();
        mainPanel = this.mainPanel;//new com.wildc.ucumari.client.base.component.UPanelMant();
        buttonBar = new com.wildc.ucumari.client.base.component.UPanel();
        btnAceptar = new com.wildc.ucumari.client.base.component.UToolBarButton();
        btnCancelar = new com.wildc.ucumari.client.base.component.UToolBarButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        container.setLayout(new java.awt.BorderLayout());

        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        container.add(mainPanel, java.awt.BorderLayout.CENTER);

        buttonBar.setPreferredSize(new java.awt.Dimension(400, 33));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        buttonBar.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        buttonBar.add(btnCancelar);

        container.add(buttonBar, java.awt.BorderLayout.SOUTH);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String mensaje = mainPanel.validarFormulario();
        if(Constantes.STRING_VACIO.equalsIgnoreCase(mensaje)){
            mainPanel.aceptar();
        }else{
            UMessage.showMessageAlert(parent, mensaje);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       SwingUtils.fadeOutFast(this);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UDialogMantBase dialog = new UDialogMantBase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wildc.ucumari.client.base.component.UToolBarButton btnAceptar;
    private com.wildc.ucumari.client.base.component.UToolBarButton btnCancelar;
    private com.wildc.ucumari.client.base.component.UPanel buttonBar;
    private com.wildc.ucumari.client.base.component.UPanel container;
    private com.wildc.ucumari.client.base.component.UPanelMant mainPanel;
    // End of variables declaration//GEN-END:variables
}
