/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.wildc.ucumari.client.base;

import com.wildc.ucumari.client.base.util.Constantes;
import com.wildc.ucumari.security.model.UserLogin;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Cristian
 */
public class UInternalBaseMant extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public UInternalBaseMant() {
        super();
        
        initComponents();
        List<UserLogin> listU = new ArrayList<UserLogin>();
        UserLogin userL = null;
        for(int i=0; i<15; i++){
            userL = new UserLogin();
            userL.setPartyCompanyId("company" + (i+1));
            userL.setUserLoginId("user ");
            userL.setCurrentPassword("password");
            listU.add(userL);
        }
        
        List<String> lisCont = new ArrayList<String>();
        lisCont.add("partyCompanyId");
        lisCont.add("currentPassword");
        lisCont.add("userLoginId");
        tblDatos.setDomainClass(UserLogin.class);
        tblDatos.setListContenido(lisCont);
        tblDatos.setListObject(listU);
        /*
        this.setBorder(
            javax.swing.BorderFactory.
      createTitledBorder(null, "title", javax.swing.border.
      TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.
      TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));*/
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new com.wildc.ucumari.client.base.component.UPanel();
        toolBar = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g) {
                //super.paintComponent(g);
                g.setColor(Constantes.BACKGROUND_TOOLBAR_INTERNAL_FRAME);
                g.fillRect(0,0,getWidth(), getHeight());
            }};
            btnNuevo = new com.wildc.ucumari.client.base.component.UToolBarButton();
            btnModificar = new com.wildc.ucumari.client.base.component.UToolBarButton();
            btnEliminar = new com.wildc.ucumari.client.base.component.UToolBarButton();
            mainContainerPanel = new com.wildc.ucumari.client.base.component.UPanel();
            pnlBusqueda = new com.wildc.ucumari.client.base.component.UPanel();
            pnlFiltro = new com.wildc.ucumari.client.base.component.UPanel();
            pnlBotonera = new com.wildc.ucumari.client.base.component.UPanel();
            btnBuscar = new com.wildc.ucumari.client.base.component.UToolBarButton();
            pnlDetalleBusqueda = new com.wildc.ucumari.client.base.component.UPanel();
            tblDatos = new com.wildc.ucumari.client.base.component.UTable<UserLogin>();

            setClosable(true);
            setMaximizable(true);
            setResizable(true);
            setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/logo.png"))); // NOI18N
            getContentPane().setLayout(null);

            container.setLayout(new java.awt.BorderLayout());

            toolBar.setOpaque(false);
            toolBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

            btnNuevo.setBackground(Constantes.BACKGROUND_BUTTON_WINDOW);
            btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/agregar_disabled.png"))); // NOI18N
            btnNuevo.setMnemonic('N');
            btnNuevo.setToolTipText("Nuevo");
            btnNuevo.setMaximumSize(new java.awt.Dimension(60, 30));
            btnNuevo.setMinimumSize(new java.awt.Dimension(60, 30));
            btnNuevo.setPreferredSize(new java.awt.Dimension(60, 30));
            btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/agregar_enabled.png"))); // NOI18N
            btnNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnNuevoActionPerformed(evt);
                }
            });
            toolBar.add(btnNuevo);

            btnModificar.setBackground(Constantes.BACKGROUND_BUTTON_WINDOW);
            btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/editar_disabled.png"))); // NOI18N
            btnModificar.setMnemonic('N');
            btnModificar.setToolTipText("Modificar");
            btnModificar.setMaximumSize(new java.awt.Dimension(60, 30));
            btnModificar.setMinimumSize(new java.awt.Dimension(60, 30));
            btnModificar.setPreferredSize(new java.awt.Dimension(60, 30));
            btnModificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/editar_enabled.png"))); // NOI18N
            btnModificar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnModificarActionPerformed(evt);
                }
            });
            toolBar.add(btnModificar);

            btnEliminar.setBackground(Constantes.BACKGROUND_BUTTON_WINDOW);
            btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/borrar_disabled.png"))); // NOI18N
            btnEliminar.setMnemonic('N');
            btnEliminar.setToolTipText("Eliminar");
            btnEliminar.setMaximumSize(new java.awt.Dimension(60, 30));
            btnEliminar.setMinimumSize(new java.awt.Dimension(60, 30));
            btnEliminar.setPreferredSize(new java.awt.Dimension(60, 30));
            btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/borrar_enabled.png"))); // NOI18N
            btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEliminarActionPerformed(evt);
                }
            });
            toolBar.add(btnEliminar);

            container.add(toolBar, java.awt.BorderLayout.NORTH);

            mainContainerPanel.setBackground(new java.awt.Color(255, 153, 153));
            mainContainerPanel.setOpaque(false);
            mainContainerPanel.setPreferredSize(new java.awt.Dimension(30, 30));
            mainContainerPanel.setLayout(new java.awt.BorderLayout());

            java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/wildc/ucumari/resources/properties/messages"); // NOI18N
            pnlBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), bundle.getString("panel.busqueda"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white)); // NOI18N
            pnlBusqueda.setMinimumSize(new java.awt.Dimension(180, 100));
            pnlBusqueda.setPreferredSize(new java.awt.Dimension(180, 100));
            pnlBusqueda.setLayout(new java.awt.BorderLayout());

            pnlFiltro.setLayout(null);
            pnlBusqueda.add(pnlFiltro, java.awt.BorderLayout.CENTER);

            pnlBotonera.setLayout(new java.awt.BorderLayout(50, 0));

            btnBuscar.setBackground(Constantes.BACKGROUND_BUTTON_WINDOW);
            btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/borrar_disabled.png"))); // NOI18N
            btnBuscar.setMnemonic('N');
            btnBuscar.setText("Buscar");
            btnBuscar.setToolTipText("Eliminar");
            btnBuscar.setMaximumSize(new java.awt.Dimension(60, 30));
            btnBuscar.setMinimumSize(new java.awt.Dimension(60, 30));
            btnBuscar.setPreferredSize(new java.awt.Dimension(110, 30));
            btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/borrar_enabled.png"))); // NOI18N
            btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscarActionPerformed(evt);
                }
            });
            pnlBotonera.add(btnBuscar, java.awt.BorderLayout.EAST);

            pnlBusqueda.add(pnlBotonera, java.awt.BorderLayout.SOUTH);

            mainContainerPanel.add(pnlBusqueda, java.awt.BorderLayout.NORTH);

            pnlDetalleBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
            pnlDetalleBusqueda.setLayout(new java.awt.BorderLayout());
            pnlDetalleBusqueda.add(tblDatos, java.awt.BorderLayout.CENTER);

            mainContainerPanel.add(pnlDetalleBusqueda, java.awt.BorderLayout.CENTER);

            container.add(mainContainerPanel, java.awt.BorderLayout.CENTER);

            getContentPane().add(container);
            container.setBounds(0, 5, 390, 260);
            setSize(660, 400);
            setContentPane(container);
            mainContainerPanel.setOpaque(false);
            container.setOpaque(false);
            //toolBar.setSize(660, 40);
            setVisible(true);
            getRootPane().setOpaque(false);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        agregar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void agregar(){
        
        
    }
    
    public void modificar(){
        
    }
    
    public void eliminar(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wildc.ucumari.client.base.component.UToolBarButton btnBuscar;
    private com.wildc.ucumari.client.base.component.UToolBarButton btnEliminar;
    private com.wildc.ucumari.client.base.component.UToolBarButton btnModificar;
    private com.wildc.ucumari.client.base.component.UToolBarButton btnNuevo;
    private com.wildc.ucumari.client.base.component.UPanel container;
    private com.wildc.ucumari.client.base.component.UPanel mainContainerPanel;
    private com.wildc.ucumari.client.base.component.UPanel pnlBotonera;
    private com.wildc.ucumari.client.base.component.UPanel pnlBusqueda;
    private com.wildc.ucumari.client.base.component.UPanel pnlDetalleBusqueda;
    private com.wildc.ucumari.client.base.component.UPanel pnlFiltro;
    private com.wildc.ucumari.client.base.component.UTable tblDatos;
    private javax.swing.JPanel toolBar;
    // End of variables declaration//GEN-END:variables
}
