/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.wildc.ucumari.party.client;

import com.wildc.ucumari.client.base.UDialogMantBase;
import com.wildc.ucumari.client.base.UInternalBaseMant;
import com.wildc.ucumari.client.base.util.Conexion;
import com.wildc.ucumari.party.model.Person;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author cmontes
 */
public class ListaEmpleados extends UInternalBaseMant {

    JFrame parent = null;
    /**
     * Creates new form ListaEmpleados1
     */
    public ListaEmpleados(JFrame parent) {
        super();
        this.parent = parent;
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void buscar() {
        try {
            List<Person> lista = Conexion.getPartyDelegate().findWorkers();
            
            
            

            List<String> lisCont = new ArrayList<String>();
            lisCont.add("partyId");
            lisCont.add("firstName");
            lisCont.add("lastName");
            tblDatos.setDomainClass(Person.class);
            tblDatos.setListContenido(lisCont);
            tblDatos.setListObject(lista);
        } catch (Exception ex) {
            Logger.getLogger(ListaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
    }

    @Override
    public void agregar() {
        //Empleado dialog = new Empleado(parent, true);
       UDialogMantBase dialog = new UDialogMantBase(parent, "Detalle Empleado", true, new PnlEmpleado());
       // UDialogBase dialog = new UDialogBase(parent, true);
        //SwingUtils.createDialogBackPanel(dialog, parent);
    }
}
