/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.wildc.ucumari.party.client;

import com.wildc.ucumari.client.base.component.UComboBoxModel;
import com.wildc.ucumari.client.base.component.UPanelMant;
import com.wildc.ucumari.client.base.util.Conexion;
import static com.wildc.ucumari.client.base.util.Conexion.getPartyDelegate;
import com.wildc.ucumari.client.base.util.Constantes;
import com.wildc.ucumari.parameters.model.RoleType;
import com.wildc.ucumari.party.model.Person;
import com.wildc.ucumari.security.model.UserLogin;

/**
 *
 * @author cmontes
 */
public class PnlEmpleado extends UPanelMant {

    /**
     * Creates new form PnlEmpleado
     */
    public PnlEmpleado() {
        initComponents();      
        fillComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPartiyId = new javax.swing.JLabel();
        txtPartyId = new com.wildc.ucumari.client.base.component.UTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new com.wildc.ucumari.client.base.component.UTextField();
        lblApepat = new javax.swing.JLabel();
        txtApepat = new com.wildc.ucumari.client.base.component.UTextField();
        lblFechNac = new javax.swing.JLabel();
        txtApemat = new com.wildc.ucumari.client.base.component.UTextField();
        lblNroDoc = new javax.swing.JLabel();
        dateFechNac = new com.wildc.ucumari.client.base.component.UDatePicker();
        lblPassword = new javax.swing.JLabel();
        cmbTipoDoc = new com.wildc.ucumari.client.base.component.UComboBox();
        lblTipoDoc = new javax.swing.JLabel();
        uTextField1 = new com.wildc.ucumari.client.base.component.UTextField();
        lblApemat = new javax.swing.JLabel();
        txtUsuario = new com.wildc.ucumari.client.base.component.UTextField();
        lblRolEmpleado = new javax.swing.JLabel();
        txtConstrasenia2 = new com.wildc.ucumari.client.base.component.UPasswordField();
        lblPassword1 = new javax.swing.JLabel();
        txtConstrasenia1 = new com.wildc.ucumari.client.base.component.UPasswordField();
        lblLogin1 = new javax.swing.JLabel();
        cmbRolEmpleados = new com.wildc.ucumari.client.base.component.UComboBox();

        setMinimumSize(new java.awt.Dimension(500, 250));
        setPreferredSize(new java.awt.Dimension(500, 250));
        setLayout(null);

        lblPartiyId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPartiyId.setForeground(new java.awt.Color(255, 255, 255));
        lblPartiyId.setText("Código:");
        add(lblPartiyId);
        lblPartiyId.setBounds(20, 30, 70, 14);

        txtPartyId.setEditable(false);
        txtPartyId.setMinimumSize(new java.awt.Dimension(4, 20));
        txtPartyId.setPreferredSize(new java.awt.Dimension(4, 20));
        add(txtPartyId);
        txtPartyId.setBounds(120, 30, 110, 20);

        lblNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("Nombres:");
        add(lblNombres);
        lblNombres.setBounds(20, 65, 70, 14);

        txtNombres.setMargin(new java.awt.Insets(-5, 2, -5, 2));
        txtNombres.setMinimumSize(new java.awt.Dimension(6, 20));
        txtNombres.setPreferredSize(new java.awt.Dimension(6, 20));
        txtNombres.setRequired(true);
        add(txtNombres);
        txtNombres.setBounds(120, 65, 110, 20);

        lblApepat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApepat.setForeground(new java.awt.Color(255, 255, 255));
        lblApepat.setText("Apellido Paterno:");
        add(lblApepat);
        lblApepat.setBounds(240, 65, 100, 20);

        txtApepat.setMargin(new java.awt.Insets(-4, 2, -4, 2));
        txtApepat.setMinimumSize(new java.awt.Dimension(6, 20));
        txtApepat.setPreferredSize(new java.awt.Dimension(6, 20));
        txtApepat.setRequired(true);
        add(txtApepat);
        txtApepat.setBounds(350, 65, 110, 20);

        lblFechNac.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFechNac.setForeground(new java.awt.Color(255, 255, 255));
        lblFechNac.setText("Fecha Nacimiento:");
        add(lblFechNac);
        lblFechNac.setBounds(240, 100, 110, 20);

        txtApemat.setMargin(new java.awt.Insets(-2, 2, -2, 2));
        txtApemat.setMinimumSize(new java.awt.Dimension(6, 20));
        txtApemat.setPreferredSize(new java.awt.Dimension(61, 20));
        add(txtApemat);
        txtApemat.setBounds(120, 100, 110, 20);

        lblNroDoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNroDoc.setForeground(new java.awt.Color(255, 255, 255));
        lblNroDoc.setText("Nro Documento:");
        add(lblNroDoc);
        lblNroDoc.setBounds(240, 135, 100, 20);

        dateFechNac.setMaximumSize(new java.awt.Dimension(21, 20));
        dateFechNac.setMinimumSize(new java.awt.Dimension(21, 20));
        dateFechNac.setPreferredSize(new java.awt.Dimension(21, 20));
        add(dateFechNac);
        dateFechNac.setBounds(350, 100, 120, 20);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña:");
        add(lblPassword);
        lblPassword.setBounds(20, 205, 100, 20);

        cmbTipoDoc.setForeground(new java.awt.Color(255, 255, 255));
        cmbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "PASAPORTE" }));
        add(cmbTipoDoc);
        cmbTipoDoc.setBounds(120, 135, 110, 18);

        lblTipoDoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTipoDoc.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoDoc.setText("Tipo Documento:");
        add(lblTipoDoc);
        lblTipoDoc.setBounds(20, 135, 100, 20);

        uTextField1.setMinimumSize(new java.awt.Dimension(4, 20));
        uTextField1.setPreferredSize(new java.awt.Dimension(60, 20));
        add(uTextField1);
        uTextField1.setBounds(350, 135, 110, 20);

        lblApemat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblApemat.setForeground(new java.awt.Color(255, 255, 255));
        lblApemat.setText("Apellido Materno:");
        add(lblApemat);
        lblApemat.setBounds(20, 100, 100, 20);

        txtUsuario.setMinimumSize(new java.awt.Dimension(4, 20));
        txtUsuario.setPreferredSize(new java.awt.Dimension(4, 20));
        txtUsuario.setRequired(true);
        add(txtUsuario);
        txtUsuario.setBounds(120, 170, 110, 20);

        lblRolEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRolEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblRolEmpleado.setText("Rol Empleado:");
        add(lblRolEmpleado);
        lblRolEmpleado.setBounds(240, 170, 100, 20);

        txtConstrasenia2.setMinimumSize(new java.awt.Dimension(4, 20));
        txtConstrasenia2.setPreferredSize(new java.awt.Dimension(109, 20));
        txtConstrasenia2.setRequired(true);
        add(txtConstrasenia2);
        txtConstrasenia2.setBounds(350, 205, 110, 20);

        lblPassword1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Repita Contraseña:");
        add(lblPassword1);
        lblPassword1.setBounds(240, 205, 110, 20);

        txtConstrasenia1.setMinimumSize(new java.awt.Dimension(4, 20));
        txtConstrasenia1.setPreferredSize(new java.awt.Dimension(109, 20));
        txtConstrasenia1.setRequired(true);
        add(txtConstrasenia1);
        txtConstrasenia1.setBounds(120, 205, 109, 20);

        lblLogin1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin1.setText("Usuario Sistema:");
        add(lblLogin1);
        lblLogin1.setBounds(20, 170, 100, 20);

        try{
            cmbRolEmpleados.setClazz(Class.forName("com.wildc.ucumari.parameters.model.RoleType"));
        }catch(Exception e){}
        cmbRolEmpleados.setFieldview("getDescription");
        cmbRolEmpleados.setRequired(true);
        add(cmbRolEmpleados);
        cmbRolEmpleados.setBounds(350, 170, 110, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wildc.ucumari.client.base.component.UComboBox cmbRolEmpleados;
    private com.wildc.ucumari.client.base.component.UComboBox cmbTipoDoc;
    private com.wildc.ucumari.client.base.component.UDatePicker dateFechNac;
    private javax.swing.JLabel lblApemat;
    private javax.swing.JLabel lblApepat;
    private javax.swing.JLabel lblFechNac;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNroDoc;
    private javax.swing.JLabel lblPartiyId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblRolEmpleado;
    private javax.swing.JLabel lblTipoDoc;
    private com.wildc.ucumari.client.base.component.UTextField txtApemat;
    private com.wildc.ucumari.client.base.component.UTextField txtApepat;
    private com.wildc.ucumari.client.base.component.UPasswordField txtConstrasenia1;
    private com.wildc.ucumari.client.base.component.UPasswordField txtConstrasenia2;
    private com.wildc.ucumari.client.base.component.UTextField txtNombres;
    private com.wildc.ucumari.client.base.component.UTextField txtPartyId;
    private com.wildc.ucumari.client.base.component.UTextField txtUsuario;
    private com.wildc.ucumari.client.base.component.UTextField uTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void aceptar() {
        Person person = new Person();
        person.setFirstName(txtNombres.getText());
        person.setLastName(txtApepat.getText());
        person.setBirthDate(dateFechNac.getDate());
        person.setRoleTypeId(((RoleType)cmbRolEmpleados.getSelectedItem()).getRoleTypeId());
                
        UserLogin userLogin = new UserLogin();
        userLogin.setUserLoginId(txtUsuario.getText());
        userLogin.setCurrentPassword(txtConstrasenia1.getText());
        userLogin.setPartyCompanyId(Conexion.getUserSession().getPartyCompanyId());
        userLogin.setRequirePasswordChange(com.wildc.ucumari.base.util.Constantes.Successful.YES.getCode());
        userLogin.setPerson(person);
        Conexion.getPartyDelegate().saveNewWorker(userLogin);
    }
    
    

    @Override
    public String validarFormulario() {
        if(txtNombres.getText().trim().equalsIgnoreCase(Constantes.STRING_VACIO)){
            txtNombres.requestFocus();
            return "El nombre es obligatorio";
        }
        if(txtApepat.getText().trim().equalsIgnoreCase(Constantes.STRING_VACIO)){
            txtApepat.requestFocus();
            return "El Apellido Paterno es obligatorio";
        }
        if(txtUsuario.getText().trim().equalsIgnoreCase(Constantes.STRING_VACIO)){
            txtUsuario.requestFocus();
            return "El nombre de usuario es obligatorio";
        }
        if(txtConstrasenia1.getText().trim().equalsIgnoreCase(Constantes.STRING_VACIO)){
            txtConstrasenia1.requestFocus();
            return "La Contraseña es obligatoria";
        }
        if(txtConstrasenia2.getText().trim().equalsIgnoreCase(Constantes.STRING_VACIO)){
            txtConstrasenia2.requestFocus();
            return "Repita la Contraseña";
        }
        if(!txtConstrasenia1.getText().equals(txtConstrasenia2.getText())){
            txtConstrasenia1.setText("");
            txtConstrasenia2.setText("");
            txtConstrasenia1.requestFocus();
            return "Las constraseñas deben ser iguales";
        }
        return Constantes.STRING_VACIO;
    }

    @Override
    public void fillComponents() {
        UComboBoxModel<RoleType> modelRolEmpleado = new UComboBoxModel<RoleType>();
        RoleType roleType = new RoleType();
        roleType.setParentTypeId(com.wildc.ucumari.base.util.Constantes.RoleType.EMPLOYEE.getCode());
        //Conexion.getParameterDelegate().findByParentType(roleType);
        modelRolEmpleado.addElements(Conexion.getParameterDelegate().findByParentType(roleType));
        cmbRolEmpleados.setModel(modelRolEmpleado);
    }
}
