/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.wildc.ucumari.client;

import com.wildc.ucumari.client.base.util.Constantes;
import com.wildc.ucumari.client.base.util.SwingUtils;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JFrame;

/**
 *
 * @author Cristian
 */
public class UAboutDialog extends javax.swing.JDialog {

   
    JFrame parentMain;
    
    /**
     * Creates new form UDialogBase
     */
    public UAboutDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        this.parentMain = parent;
       
        //setUndecorated(true);
        //AWTUtilities.setWindowOpaque(this, false);	
        
        initComponents();
        
        
        SwingUtils.enterPressesWhenFocused(btnCancelar);
        
        setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        container.setPreferredSize(getPreferredSize());
        container.setLayout(new java.awt.BorderLayout());
               
    }

    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g) {
                g.setColor(Constantes.BACKGROUND_ABOUT);
                g.fillRect(0,0,getWidth(), getHeight());
            }};
            pnlLogo = new javax.swing.JPanel(){
                @Override
                public void paintComponent(Graphics g) {
                    g.setColor(Constantes.BACKGROUND_ABOUT);
                    g.fillRect(0,0,getWidth(), getHeight());
                }};
                lblLogo = new javax.swing.JLabel();
                pnlDatos = new javax.swing.JPanel(){
                    @Override
                    public void paintComponent(Graphics g) {
                        g.setColor(Constantes.BACKGROUND_ABOUT);
                        g.fillRect(0,0,getWidth(), getHeight());
                    }};
                    btnCancelar = new com.wildc.ucumari.client.base.component.UToolBarButton();
                    lblAbout = new javax.swing.JLabel();

                    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/wildc/ucumari/resources/properties/applicationResources"); // NOI18N
                    setTitle(bundle.getString("login.title")); // NOI18N

                    container.setBackground(Constantes.BACKGROUND_ABOUT);
                    container.setPreferredSize(getPreferredSize());
                    container.setLayout(new java.awt.BorderLayout());

                    pnlLogo.setLayout(new java.awt.BorderLayout());

                    lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/wildc/ucumari/resources/logo.png"))); // NOI18N
                    pnlLogo.add(lblLogo, java.awt.BorderLayout.CENTER);

                    container.add(pnlLogo, java.awt.BorderLayout.WEST);

                    pnlDatos.setLayout(null);

                    btnCancelar.setBackground(Constantes.BACKGROUND_BUTTON_WINDOW);
                    btnCancelar.setMnemonic('C');
                    btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                    btnCancelar.setLabel("Aceptar");
                    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnCancelarActionPerformed(evt);
                        }
                    });
                    pnlDatos.add(btnCancelar);
                    btnCancelar.setBounds(60, 180, 90, 28);

                    lblAbout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                    lblAbout.setText("<html>Easy Sale <br>es una plataforma para gestionar tu negocio de manera Ágil y Dinámica. <br> <br> <br> All Rights reserved - Mind Business <br>Soft Labs </html>");
                    pnlDatos.add(lblAbout);
                    lblAbout.setBounds(0, 20, 240, 150);

                    container.add(pnlDatos, java.awt.BorderLayout.CENTER);

                    container.setPreferredSize(new Dimension(410,220));
                    container.setFocusable(true);
                    container.requestFocusInWindow();

                    getContentPane().add(container, java.awt.BorderLayout.CENTER);
                    //container.setBounds(0, 0, getWidth(), getHeight());

                    //SwingUtils.createLoginDialog(this, 408, 270);
                    //SwingUtils.addEscapeToCloseSupport(this, true);
                    //SwingUtils.fadeInFast(this);
                    this.setSize(438, 270);
                    this.setLocation((this.getToolkit().getScreenSize().width-this.getWidth())/2, (this.getToolkit().getScreenSize().height-this.getHeight())/2);

                    pack();
                }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wildc.ucumari.client.base.component.UToolBarButton btnCancelar;
    private javax.swing.JPanel container;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
